OPENAI_API_KEY = "your-openai-api-key"

AWS_ACCESS_KEY_ID = "your-aws-access-key-id"
AWS_SECRET_ACCESS_KEY = "your-aws-secret-access-key"
AWS_S3_BUCKET_NAME = "your-s3-bucket-name"
AWS_REGION = "your-region"  